services:
  php-apache:
    image: php:8.2-apache
    container_name: meu_php
    volumes:
      - /run/desktop/mnt/host/c/xampp/htdocs/Proj_Desenvolvimento_II_Plantagotchi/app:/var/www/html

    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: meu_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db_temp:/var/lib/mysql
    ports:
      - "3307:3306"
